name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Build and tag images
        env:
          REGISTRY: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}
        run: |
          # Build backend image
          docker build -t backend:latest ./backend
          docker tag backend:latest $REGISTRY/backend:${{ github.sha }}
          docker tag backend:latest $REGISTRY/backend:latest
          
          # Build frontend image
          docker build -t frontend:latest ./frontend
          docker tag frontend:latest $REGISTRY/frontend:${{ github.sha }}
          docker tag frontend:latest $REGISTRY/frontend:latest

      - name: Push images to DO Registry
        env:
          REGISTRY: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}
        run: |
          docker push $REGISTRY/backend:${{ github.sha }}
          docker push $REGISTRY/backend:latest
          docker push $REGISTRY/frontend:${{ github.sha }}
          docker push $REGISTRY/frontend:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /opt/urlshortener
            
            # Update environment variables
            touch .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
            echo "OCR_API_KEY=${{ secrets.OCR_API_KEY }}" >> .env
            echo "OCR_API_ENDPOINT=${{ secrets.OCR_API_ENDPOINT }}" >> .env
            echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
            echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
            echo "DIGITALOCEAN_REGISTRY=${{ secrets.DIGITALOCEAN_REGISTRY }}" >> .env
            echo "CHAT_GPT_API_KEY=${{ secrets.CHAT_GPT_API_KEY }}" >> .env

            # Pull latest images
            docker compose -f docker-compose.prod.yml pull

            # Restart services
            docker compose -f docker-compose.prod.yml up -d

            # Clean up old images
            docker image prune -f